### PR TITLE
add modbus driver for nuv_300 (low voltage bms)

### PR DESCRIPTION
**Pull request by jabbenseth**

### CODE REVIEW

**Comment by ipa-rmb** [comment]
In my comparison, everything is new and does not compare against the already existing files. Is there something wrong in this PR?

Further, the moved files e.g. from ros/src to src are also indicated as completely new.

@ipa-jba please check.

By the way, do you insist in changing the indentation? It was consistently tabs before?

**Comment by ipa-rmb** [comment]
Ping

**Comment by jabbenseth** [comment]
> In my comparison, everything is new and does not compare against the already existing files. Is there something wrong in this PR?

I updated this PR to contain only "new" changes. 

> Further, the moved files e.g. from ros/src to src are also indicated as completely new.

They are not only moved, but I split up the "library/class-part" from the "node" part -> changes to the file + moved


> By the way, do you insist in changing the indentation? It was consistently tabs before?

For new and open source packages I stick to the style guide which says 
> Indent each block by 2 spaces. Never insert literal tab characters.

Even though http://wiki.ros.org/CppStyleGuide states it is merely a guide instead of a rule, I see no harm in following it/see no reason to deviate in this case.

**Comment by ipa-rmb** [comment]
How do we set up Travis according to the new interface?

**Review by ipa-rmb — APPROVED** [review]

**Comment by ipa-rmb** [comment]
Ah, just found it.

**Review by ipa-rmb — APPROVED** [review]

**Pull request merged**
